{% set name = "timescale" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c943e4e4db6db9c63813620e03b789e513c59164fde7f07f8616d03fc9651679

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - numpy
    - python-dateutil
    - scipy
    - setuptools

test:
  imports:
    - timescale
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/timescale
  summary: Python tools for time and astronomical calculations.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://timescale.readthedocs.io
  dev_url: https://github.com/pyTMD/timescale

extra:
  recipe-maintainers:
    - tsutterley
