{% set name = "timescale" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6aada4cbc6f6fcc6ce2cafbf313f613335f1954cb4288caf85da32c3b14b42f

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools
  run:
    - python >=3.6
    - lxml
    - numpy
    - python-dateutil
    - scipy
    - setuptools-scm
    - setuptools

test:
  imports:
    - timescale
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tsutterley/timescale
  summary: Python tools for time and astronomical calculations.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://timescale.readthedocs.io
  dev_url: https://github.com/tsutterley/timescale

extra:
  recipe-maintainers:
    - tsutterley
