{% set name = "timescale" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0241343931f3b1117c3d2621e17997ffaa414ebbaf301ad33330da65d1df09a

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - numpy
    - python-dateutil
    - scipy
    - setuptools-scm
    - setuptools

test:
  imports:
    - timescale
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyTMD/timescale
  summary: Python tools for time and astronomical calculations.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://timescale.readthedocs.io
  dev_url: https://github.com/pyTMD/timescale

extra:
  recipe-maintainers:
    - tsutterley
